# 将文件同步到blog仓库
name: Push to blog repo

on:
  push:
    branches: [master]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  push-to-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # 令牌
          publish_dir: ./ # 构建后的文件目录
          external_repository: hjwang1024/hjwang1024.github.io # 仓库B，格式为：user/repo
          publish_branch: master # 仓库B的分支

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Sync code to destination repository
        uses: elstudio/actions-sync@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          source_repo: hjwang1024/daydayup
          source_branch: master # 可以根据你的主要分支修改
          destination_repo: hjwang1024/hjwang1024.github.io/tree/master/docs
          destination_branch: master # 可以根据你的主要分支修改
